image: node:14.20.0

pipelines:
  branches:
    master:
      - step:
          name: Installation
          caches:
            - node
          script:
            - npm install -g @angular/cli@13.1.4
            - npm install
            - ng version
            - npm run build
          artifacts:
            - dist/** # Save build for next steps
      - step:
          name: Deploy
          deployment: Test
          script:
            - echo "$(ls -la)"
            - echo "$(ls -la dist)"
            - pipe: atlassian/ftp-deploy:0.4.0
              variables:
                USER: 'ci_holinsys@spda.misolucioneswow.com'
                PASSWORD: 'c1tT3n^5#r#e'
                SERVER: 'spda.misolucioneswow.com'
                REMOTE_PATH: 'spda.misolucioneswow.com/public_html'
                LOCAL_PATH: 'dist' # Optional
                # DEBUG: '<boolean>' # Optional
                # SET_ARGS: '<string>' # Optional.
                # EXTRA_ARGS: '<string>' # Optional.
                # DELETE_FLAG: '<boolean>' # Optional.